Remove hard-coded min and max awards
dvrpc/TCDI pull request #4
Opened 2018-03-09 21:47 UTC by DVRPCfreight

Calculates max and min award values and uses for the Mapbox GL viz

2018-03-09 22:12 UTC, jstrangfeld requested changes

2018-03-09 22:12 UTC, jstrangfeld commented on js/index.js
> +const maxAward = Math.max(...awards)
Spread is not IE11 friendly

2018-03-10 01:54 UTC, jstrangfeld approved these changes

2018-03-10 01:55 UTC, jstrangfeld commented
I would suggest squashing this when merging since Mike is so messy with his commits.

2018-03-10 02:05 UTC, DVRPCfreight commented
Hey, what do you expect I am just a lowly planner...but yes squash my mess please

2018-03-12 13:47 UTC, merged